### ISSUE TITLE
Modification mineure du fichier de licence

### ISSUE THREAD

**Issue by boisgera** [timotheedol/AP_cours#1]
Dans le fichier de licence, remplacer

    licence open-source simple et permissive

    Timothée Dol 

    2022

    MIT License

    Copyright (c) [year] [fullname]

par 

    MIT License

    Copyright (c) 2022 Timothée Dol

puis s'assurer que dans la colonne de droite de la page principale du projet, GitHub a détecté le type de licence (MIT).

**Comment by timotheedol** [comment]
Normalement j'ai satisfait la demande!
commit a94346509d7d217e7b8bf5c1dbd431caa18dbc88

**Comment by boisgera** [comment]
👍
